"""update_vector_dimensions_to_3072

Revision ID: 553a7346f34d
Revises: 913acfd7890d
Create Date: 2025-10-25 19:23:32.162130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '553a7346f34d'
down_revision: Union[str, None] = '913acfd7890d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunity_embeddings', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=3072),
               comment='3072-dimensional embedding vector',
               existing_comment='1536-dimensional embedding vector',
               existing_nullable=False)
    op.alter_column('user_embeddings', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=3072),
               comment='3072-dimensional embedding vector',
               existing_comment='1536-dimensional embedding vector',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_embeddings', 'embedding',
               existing_type=Vector(dim=3072),
               type_=Vector(dim=1536),
               comment='1536-dimensional embedding vector',
               existing_comment='3072-dimensional embedding vector',
               existing_nullable=False)
    op.alter_column('opportunity_embeddings', 'embedding',
               existing_type=Vector(dim=3072),
               type_=Vector(dim=1536),
               comment='1536-dimensional embedding vector',
               existing_comment='3072-dimensional embedding vector',
               existing_nullable=False)
    # ### end Alembic commands ###

