"""add_embeddings_and_hard_filters

Revision ID: 913acfd7890d
Revises: 5bd4932ea643
Create Date: 2025-10-25 19:01:58.555481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '913acfd7890d'
down_revision: Union[str, None] = '5bd4932ea643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_embeddings',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='OpenAI model used (e.g., text-embedding-3-large)'),
    sa.Column('text_for_embedding', sa.Text(), nullable=False, comment='Combined text: title + description + research_topics'),
    sa.Column('embedding', Vector(1536), nullable=False, comment='1536-dimensional embedding vector'),
    sa.Column('embedded_at', sa.DateTime(), nullable=False, comment='When embedding was generated'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.opportunity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    op.create_table('user_embeddings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='OpenAI model used (e.g., text-embedding-3-large)'),
    sa.Column('text_for_embedding', sa.Text(), nullable=False, comment='Copy of research_interests text used for embedding'),
    sa.Column('embedding', Vector(1536), nullable=False, comment='1536-dimensional embedding vector'),
    sa.Column('embedded_at', sa.DateTime(), nullable=False, comment='When embedding was generated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('opportunities', sa.Column('location_city', sa.String(length=100), nullable=True, comment='City where position is located'))
    op.add_column('opportunities', sa.Column('location_state', sa.String(length=2), nullable=True, comment="State code (e.g., 'CA', 'NY')"))
    op.add_column('opportunities', sa.Column('is_remote', sa.Boolean(), nullable=False, comment='Can be done remotely'))
    op.add_column('opportunities', sa.Column('degree_levels', sa.ARRAY(sa.String()), nullable=True, comment="Accepted degree levels: ['undergraduate', 'masters', 'phd']"))
    op.add_column('opportunities', sa.Column('min_hours', sa.Integer(), nullable=True, comment='Minimum hours per week expected'))
    op.add_column('opportunities', sa.Column('max_hours', sa.Integer(), nullable=True, comment='Maximum hours per week allowed'))
    op.add_column('opportunities', sa.Column('paid_type', sa.String(length=50), nullable=True, comment="Type of compensation: 'stipend', 'hourly', 'unpaid', 'credit'"))
    op.create_index(op.f('ix_opportunities_location_state'), 'opportunities', ['location_state'], unique=False)
    op.add_column('users', sa.Column('university', sa.String(length=255), nullable=True, comment="Student's current university"))
    op.add_column('users', sa.Column('major', sa.String(length=255), nullable=True, comment="Student's major/field of study"))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True, comment='Expected or actual graduation year'))
    op.add_column('users', sa.Column('gpa', sa.String(length=10), nullable=True, comment='GPA (optional)'))
    op.add_column('users', sa.Column('resume_file_path', sa.String(length=500), nullable=True, comment='Path to uploaded resume PDF file'))
    op.add_column('users', sa.Column('resume_text', sa.Text(), nullable=True, comment='Parsed resume text or summary'))
    op.add_column('users', sa.Column('past_experiences', sa.JSON(), nullable=True, comment='List of past research/work experiences'))
    op.add_column('users', sa.Column('skills', sa.JSON(), nullable=True, comment='List of technical skills'))
    op.add_column('users', sa.Column('publications', sa.JSON(), nullable=True, comment='List of publications/papers'))
    op.add_column('users', sa.Column('degree_level', sa.String(length=50), nullable=False, comment='undergraduate, masters, phd'))
    op.alter_column('users', 'location_preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment="Array of preferred state codes: ['CA', 'NY', 'MA']",
               existing_comment='List of preferred locations',
               existing_nullable=True)
    op.drop_column('users', 'experience_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='undergraduate, graduate, postdoc, independent'))
    op.alter_column('users', 'location_preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of preferred locations',
               existing_comment="Array of preferred state codes: ['CA', 'NY', 'MA']",
               existing_nullable=True)
    op.drop_column('users', 'degree_level')
    op.drop_column('users', 'publications')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'past_experiences')
    op.drop_column('users', 'resume_text')
    op.drop_column('users', 'resume_file_path')
    op.drop_column('users', 'gpa')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'major')
    op.drop_column('users', 'university')
    op.drop_index(op.f('ix_opportunities_location_state'), table_name='opportunities')
    op.drop_column('opportunities', 'paid_type')
    op.drop_column('opportunities', 'max_hours')
    op.drop_column('opportunities', 'min_hours')
    op.drop_column('opportunities', 'degree_levels')
    op.drop_column('opportunities', 'is_remote')
    op.drop_column('opportunities', 'location_state')
    op.drop_column('opportunities', 'location_city')
    op.drop_table('user_embeddings')
    op.drop_table('opportunity_embeddings')
    # ### end Alembic commands ###

